name: Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.tf'
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  validate-and-plan:
    runs-on: [self-hosted, homelab]

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Setup secrets
        run: |-
          cat <<'eof' > kubernetes-admin.conf
          ${{ secrets.KUBERNETES_ADMIN_CONF }}
          eof
 
      - name: Run Terraform Init
        run: terraform init
        
      - name: Run Terraform Format
        run: terraform fmt -check
        
      - name: Run Terraform Validate
        run: terraform validate -no-color

      - name: Run Terraform Plan
        run: terraform plan -no-color

  apply:
    needs: [validate-and-plan]
    runs-on: [self-hosted, homelab]

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Setup secrets
        run: |-
          cat <<'eof' > kubernetes-admin.conf
          ${{ secrets.KUBERNETES_ADMIN_CONF }}
          eof

      - name: Run Terraform Init
        run: terraform init

      - name: Run Terraform Apply
        run: terraform apply -no-color -auto-approve

